blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name = 'post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
	url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
	url(r'^$', views.project_list, name='project_list'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from home import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace = "blog")),
    url(r'^portfolio/', include('portfolio.urls', namespace = "portfolio")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', ('home.views.homeImage')),
    url(r'^about/', ('home.views.about')),
    url(r'^contact/', ('home.views.contact')),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.conf.urls import url
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
   # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^project/(?P<pk>[0-9]+)/$', views.ProjectView.as_view(), name='project'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.MEDIA_ROOT,
            }),

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.STATIC_ROOT,
            }),
]

'''

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]
'''

portfolio/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
'''
    
class Project_name(models.Model):
    name = models.CharField(max_length=250)
    url = models.URLField(blank=True)
    
    class Meta:
        db_table = "name"
        ordering = ['name']
    class Admin:
        pass
        
    def __repr__(self):
        return self.name
    
class Medium(models.Model):
    name = models.CharField(max_length=250)
    
    class Meta:
        db_table = "media"
        verbose_name_plural = "media"
        ordering = ['name']

    class Admin:
        pass
    
    def __repr__(self):
        return self.name
'''    
class Project(models.Model):
    projecttitle = models.CharField(max_length=200, null=True)
    projectdate = models.CharField(max_length=200, null=True)
    projectmedium = models.CharField(max_length=200, null=True)
    projecttext = models.TextField(null=True, blank=True)
    pub_date = models.DateTimeField('date published', null=True, blank=True)

    
    projectimage = models.ImageField(upload_to='', height_field=None, width_field=None, max_length=100, default='https://pmcdeadline2.files.wordpress.com/2010/08/nicolas_cage.jpg')
    '''
    def publish(self):
        
        self.save()

    def __str__(self):
        return self.projecttitle
'''
    
    def __str__(self):
        return self.projecttitle
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now    
    

portfolio/views.py
from django.shortcuts import get_object_or_404, render
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.views.generic.detail import SingleObjectMixin



from .models import Question
from .models import Project
'''

class IndexView(generic.ListView):
    template_name = 'portfolio/index.html'
    context_object_name = 'latest_question_list'
    paginate_by = 5

    def get_queryset(self):
	    i=0
	    x=i+5

	    """
	    Return the last five published questions (not including those set to be
	    published in the future).
	    """
	    return Question.objects.filter( 
	    	pub_date__lte=timezone.now()
	    ).order_by('-pub_date')
'''

class DetailView(generic.DetailView):
    ...
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ProjectView(generic.DetailView):
    template_name = 'portfolio/project_detail.html'



    def get_context_data(self, **kwargs):
        context = super(ProjectView, self).get_context_data(**kwargs)
        context['projects'] = Project.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
        return context    

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Project.objects.filter(pub_date__lte=timezone.now())
        # projectDetail_list = Project.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
        #return render(request, 'portfolio/project_list.html', {'project': projects})    

class IndexView(generic.ListView):
    template_name = 'portfolio/index.html'
    context_object_name = 'project_list'
    

    def get_queryset(self):
        

        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Project.objects.filter( 
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')


class DetailView(generic.DetailView):
    ...
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())



class ResultsView(generic.DetailView):
    model = Question
    template_name = 'portfolio/results.html'

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'portfolio/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('portfolio:results', args=(p.id,)))

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'portfolio/detail.html', {'question': question})

    '''
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'portfolio/index.html', context)

def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'portfolio/results.html', {'question': question})
'''

def project_list(request):
    project_list = Project.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'portfolio/project_list.html', {'project': projects})

def projectDetail_list(request):
    projectDetail_list = Project.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'portfolio/project_list.html', {'project': projects})    

portfolio/templates/portfolio/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
     <!--   <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">-->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/portfolio_list.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Nunito:400,700' rel='stylesheet' type='text/css'>        
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

        <title>Mark of the Lam</title>

          <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
        .row.content {height: 1500px}
        
        /* Set gray background color and 100% height */
        .sidenav {
          
          height: 100%;
        }
        
        /* Set black background color, white text and some padding */
       
        
        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
          .sidenav {
            height: auto;
            padding: 15px;
          }
          .row.content {height: auto;} 
        }
      </style>
    </head>
<body>

<div class="container">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <div class="logo">
            <h1><a href="/"><img src="http://markofthelam.com/static/ml_des_optimize1.gif"></a></h1>
            </div>
        
                <div class ="navigation">
                <h1><a href="/portfolio/">work</a></h1>
                <h1><a href="/blog">blog</a></h1>
                <h1><a href="/about">about</a></h1>
                <h1><a href="/contact">contact</a></h1>
                </div>
            </div>
 
    <div class="contentBox">
    <div class="col-sm-9">
               {% block projectDetail %}
            {% endblock projectDetail %}
            <div class="projlis">
    {% block projectlist %}            
    {% for project in project_list %}
        <ul class = "list" style="list-style-type:none">
        <div class = "portfolio_list">
            <div class = "project-title">
                <li><h1><a href="{% url 'portfolio:project' project.id %}">{{ project.projecttitle }}</a></h1></li>
            </div>

            <div class = "project-image">
                <img src=' emceelamb.pythonanywhere.com/{{ project.projectimage.url }}'>
            </div>
        </div>
        </ul>
    {% endfor %}
    {% endblock %}    
      
      </div>
    </div>
</div>
  </div>
</div>



</body>
</html>

portfolio/templates/portfolio/base_detail.html
{% load staticfiles %}




            {% if projectDetail_list %}
                
                {% for project in projectDetail_list %}
                <ul class = "list" style="list-style-type:none">
                <div class = "portfolio_list">
                    <div class = "project-title">
                    <li><h1><a href="{% url 'portfolio:project' project.id %}">{{ project.projecttitle }}</a></h1></li>
                    </div>

                                    <div class = "project-image">
                                    <img src=' http://127.0.0.1:8000/portfolio{{ project.projectimage.url }}'>
                                </div>
                            </div>
                            </ul>
                {% endfor %}
                
            {% else %}
                <p>No polls sqqqa available.</p>
            {% endif %}

            </div>
        </div>
    </div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
 
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
 
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>        

portfolio/templates/portfolio/inde2x.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Nunito:400,700' rel='stylesheet' type='text/css'>        
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
        <title>Mark of the Lam</title>
    </head>
   <body>
        <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus">a</span></a>
        <div class="logo">
        <h1><a href="/"><img src="http://markofthelam.com/images/ml_des_optimize1.gif"></a></h1>
    </div>
    <div class="navigation container">
         <div class="row1">
            <div class="col-md-7">
              <div class ="navigation">
                <h1><a href="http://127.0.0.1:8000/portfolio/">work</a></h2>
                <h1><a href="">blog</a></h2>
                <h1><a href="">about</a></h2>
                <h1><a href="">contact</a></h2>
    </div>
            </div>
        </div>
    </div>


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><h1><a href="{% url 'portfolio:detail' question.id %}">{{ question.question_text }}</a></h1></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

 
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
 
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
 
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
</html>

portfolio/templates/portfolio/index.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/portfolio_list.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Nunito:400,700' rel='stylesheet' type='text/css'>        
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
        <title>Mark of the Lam</title>
    </head>
   <body>
        
        <div class="logo">
        <h1><a href="/"><img src="http://markofthelam.com/images/ml_des_optimize1.gif"></a></h1>
    </div>
    <div class="navigation container">
         <div class="row1">
            <div class="col-md-7">
              <div class ="navigation">
                <h1><a href="http://127.0.0.1:8000/portfolio/">work</a></h2>
                <h1><a href="">blog</a></h2>
                <h1><a href="">about</a></h2>
                <h1><a href="">contact</a></h2>
    </div>
            </div>
        </div>
    </div>

    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            
            {% if project_list %}
                
                {% for project in project_list %}
                <ul class = "list" style="list-style-type:none">
                <div class = "portfolio_list">
                    <div class = "project-title">
                    <li><h1><a href="{% url 'portfolio:project' project.id %}">{{ project.projecttitle }}</a></h1></li>
                    </div>

                                    <div class = "project-image">
                                    <img src=' http://127.0.0.1:8000/portfolio{{ project.projectimage.url }}'>
                                </div>
                            </div>
                            </ul>
                {% endfor %}
                
            {% else %}
                <p>No polls are available.</p>
            {% endif %}

            </div>
        </div>
    </div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
 
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
 
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

portfolio/templates/portfolio/polls.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Nunito:400,700' rel='stylesheet' type='text/css'>        
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
        <title>Mark of the Lam</title>
    </head>
   <body>
        <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus">a</span></a>
        <div class="logo">
        <h1><a href="/"><img src="http://markofthelam.com/images/ml_des_optimize1.gif"></a></h1>
    </div>
    <div class="navigation container">
         <div class="row1">
            <div class="col-md-7">
              <div class ="navigation">
                <h1><a href="http://127.0.0.1:8000/portfolio/">work</a></h2>
                <h1><a href="">blog</a></h2>
                <h1><a href="">about</a></h2>
                <h1><a href="">contact</a></h2>
    </div>
            </div>
        </div>
    </div>


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><h1><a href="{% url 'portfolio:detail' question.id %}">{{ question.question_text }}</a></h1></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

 
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
 
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
 
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
</html>

portfolio/templates/portfolio/pollsindex.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Nunito:400,700' rel='stylesheet' type='text/css'>        
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
        <title>Mark of the Lam</title>
    </head>
   <body>
        <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus">a</span></a>
        <div class="logo">
        <h1><a href="/"><img src="http://markofthelam.com/images/ml_des_optimize1.gif"></a></h1>
    </div>
    <div class="navigation container">
         <div class="row1">
            <div class="col-md-7">
              <div class ="navigation">
                <h1><a href="http://127.0.0.1:8000/portfolio/">work</a></h2>
                <h1><a href="">blog</a></h2>
                <h1><a href="">about</a></h2>
                <h1><a href="">contact</a></h2>
    </div>
            </div>
        </div>
    </div>


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><h1><a href="{% url 'portfolio:detail' question.id %}">{{ question.question_text }}</a></h1></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

 
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
 
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
 
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
</html>

portfolio/templates/portfolio/projdetail.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Nunito:400,700' rel='stylesheet' type='text/css'>        
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
        <title>Mark of the Lam</title>
    </head>
   <body>
        <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus">a</span></a>
        <div class="logo">
        <h1><a href="/"><img src="http://markofthelam.com/images/ml_des_optimize1.gif"></a></h1>
    </div>
    <div class="navigation container">
         <div class="row1">
            <div class="col-md-7">
              <div class ="navigation">
                <h1><a href="">work</a></h2>
                <h1><a href="">blog</a></h2>
                <h1><a href="">about</a></h2>
                <h1><a href="">contact</a></h2>
    </div>
            </div>
        </div>
    </div>

    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            
                {% for project in project_list %}
                    <div class="project">
                        <div class = "project-image">
                        {{ project.projectimage }}
                    </div>
                        <div class="project-title">
                        <h1><a href="{% url 'project_detail' pk=project.pk %}">{{ project.projecttitle }}</a></h1>, {{ project.projectdate}}</div>
                        <div class="project-medium">
                            <p>{{ project.projectmedium| safe }}</p>
                        </div>
                        <div class="project-text">
                            <p>{{ project.projecttext| safe }}</p>
                        </div>        
                    </div>
                {% endfor %}


            </div>
        </div>
    </div>
</body>
</html>

portfolio/templates/portfolio/project_detail.html
{% extends 'portfolio/base.html' %}

             {% block projectDetail %}   
            <div class="projectDetail">
            
            <div class="projectDetail-title">
            <h1>{{ project.projecttitle }}</a></h1></div>
            <div class = "projectDetail-image">
             <img src=' http://markofthelam.com{{ project.projectimage.url }} '>
            </div>
            <div class="projectDetail-date">
                 <p>{{ project.projectdate}}</p>
             </div>
            <div class="projectDetail-medium">
                <p>{{ project.projectmedium| safe }}</p>
            </div>
            <div class="projectDetail-text">
                <p>{{ project.projecttext| safe }}</p>
            </div>    
            {% endblock %}    

{% block projectlist %}          
    <div class="linebreak"><hr/></div>
   {% for project in projects %} 
        <ul class = "list" style="list-style-type:none">
        <div class = "portfolio_list">
            <div class = "project-title">
                <li><h3><a href="{% url 'portfolio:project' project.id %}">{{ project.projecttitle}}</a></h3></li>
            </div>

            <div class = "project-image">
               <a href="{% url 'portfolio:project' project.id %}"> <img src=' http://markofthelam.com{{ project.projectimage.url }} '></a>
            </div>
        </div>
        </ul>
  {% endfor %}
{% endblock %}                

portfolio/templates/portfolio/project_list.html
{% extends 'portfolio/base.html' %}

{% block projectlist %}          
    {% for project in project_list %}
        <ul class = "list" style="list-style-type:none">
        <div class = "portfolio_list">
            <div class = "project-title">
                <li><h3><a href="{% url 'portfolio:project' project.id %}">{{ project.projecttitle }}</a></h3></li>
            </div>

            <div class = "project-image">
                <a href="{% url 'portfolio:project' project.id %}"><img src=' http://markofthelam.com{{ project.projectimage.url }}'></a>
            </div>
        </div>
        </ul>
    {% endfor %}
{% endblock %}                

portfolio/templates/portfolio/projects - Copy.html
{% load staticfiles %}

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'portfolio/style.css' %}">
<link href='https://fonts.googleapis.com/css?family=Nunito:400,700' rel='stylesheet' type='text/css'>        
<link href='https://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><h1><a href="{% url 'portfolio:detail' question.id %}">{{ question.question_text }}</a></h1></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

 
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
 
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
 
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

portfolio/templates/portfolio/projects.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Nunito:400,700' rel='stylesheet' type='text/css'>        
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
        <title>Mark of the Lam</title>
    </head>
   <body>
        <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus">a</span></a>
        <div class="logo">
        <h1><a href="/"><img src="http://markofthelam.com/images/ml_des_optimize1.gif"></a></h1>
    </div>
    <div class="navigation container">
         <div class="row1">
            <div class="col-md-7">
              <div class ="navigation">
                <h1><a href="">work</a></h2>
                <h1><a href="">blog</a></h2>
                <h1><a href="">about</a></h2>
                <h1><a href="">contact</a></h2>
    </div>
            </div>
        </div>
    </div>

    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            
                {% for project in projects %}
                    <div class="project">
                        <div class = "project-image">
                        {{ project.projectimage }}
                    </div>
                        <div class="project-title">
                        <h1><a href="{% url 'project_detail' pk=project.pk %}">{{ project.projecttitle }}</a></h1>, {{ project.projectdate}}</div>
                        <div class="project-medium">
                            <p>{{ project.projectmedium| safe }}</p>
                        </div>
                        <div class="project-text">
                            <p>{{ project.projecttext| safe }}</p>
                        </div>        
                    </div>
                {% endfor %}


            </div>
        </div>
    </div>
</body>
</html>

portfolio/templates/portfolio/question_detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'portfolio:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

portfolio/templates/portfolio/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'portfolio:detail' question.id %}">Vote again?</a>