blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name = 'post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
	url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
	url(r'^$', views.project_list, name='project_list'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from home import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace = "blog")),
    url(r'^portfolio/', include('portfolio.urls', namespace = "portfolio")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', ('home.views.homeImage')),
    url(r'^about/', ('home.views.about')),
    url(r'^contact/', ('home.views.contact')),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)
    projectimage = models.ImageField(upload_to='', height_field=None, width_field=None, max_length=100, default='https://pmcdeadline2.files.wordpress.com/2010/08/nicolas_cage.jpg')

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

blog/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post
from django.shortcuts import render, get_object_or_404
from .forms import PostForm
from django.shortcuts import redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.


def post_list(request):
	
	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
	paginator = Paginator(posts, 5) # Show 25 contacts per page

	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		posts = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		posts = paginator.page(paginator.num_pages)
	return render(request, 'blog/post_list.html', {'posts': posts})    

	"""
	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[:5]
	return render(request, 'blog/post_list.html', {'posts': posts})
	"""


def post_detail(request, pk):
	post = get_object_or_404(Post, pk=pk)
	return render(request, 'blog/post_detail.html', {'post': post})

def post_new(request):
	
	
	if request.method == "POST":
	    
		form = PostForm(request.POST)
	    
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			return redirect('blog.views.post_detail', pk=post.pk)
		
	else:
			
		form = PostForm()
    
	return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog.views.post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

def project_list(request):
	projects = Post.objects.filter
	return render(request, 'blog/project_list.html', {'projects': projects})

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
     <!--   <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">-->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Nunito:400,700' rel='stylesheet' type='text/css'>        
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

        <title>Mark of the Lam</title>

          <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
        .row.content {height: 1500px}
        
        /* Set gray background color and 100% height */
        .sidenav {
          
          height: 100%;
        }
        
        /* Set black background color, white text and some padding */
       
        
        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
          .sidenav {
            height: auto;
            padding: 15px;
          }
          .row.content {height: auto;} 
        }
      </style>
    </head>
<body>

<div class="container">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <div class="logo">
            <h1><a href="/"><img src="http://markofthelam.com/static/ml_des_optimize1.gif"></a></h1>
            </div>
        
                <div class ="navigation">
                <h1><a href="/portfolio/">work</a></h1>
                <h1><a href="/blog">blog</a></h1>
                <h1><a href="/about">about</a></h1>
                <h1><a href="/contact">contact</a></h1>
                </div>
            </div>
 
    <div class="contentBox">
    <div class="col-sm-9">
          {% block content %}
    
            {% endblock %}
      
      </div>
    </div>
</div>
  </div>
</div>



</body>
</html>

blog/templates/blog/navigation.html
{% extends 'blog/base.html' %}

{% block navigation %}
   <div class ="navigation">
        <a href="C:\py\web\blog\templates\blog\projects.html">work</a>
	    <h2><a href="">blog</a></h2>
	    <h2><a href="">about</a></h2>
	    <h2><a href="">contact</a></h2>
	</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaks }}</p>
    </div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                 {{ post.published_date }}
            </div>
            <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <div class="post-text">
                <p>{{ post.text| safe }}</p>
            </div>    
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/project_list.html
{% extends 'portfolio/index.html' %}

{% block projectlist %}
    {% for project in projects %}
        <div class="project">
            <div class = "project-image">
                {{ project.projectimage }}
            </div>
            <div class="project-title">
                <h1><a href="{% url 'project_detail' pk=project.pk %}">{{ project.projecttitle }}</a></h1>, {{ project.projectdate}}
            </div>
            <div class="project-medium">
                <p>{{ project.projectmedium| safe }}</p>
            </div>
            <div class="project-text">
                <p>{{ project.projecttext| safe }}</p>
            </div>        
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/projects.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Nunito:400,700' rel='stylesheet' type='text/css'>        
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
        <title>Mark of the Lam</title>
    </head>
   <body>
        <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus">a</span></a>
        <div class="logo">
        <h1><a href="/"><img src="http://markofthelam.com/images/ml_des_optimize1.gif"></a></h1>
    </div>
    <div class="navigation container">
         <div class="row1">
            <div class="col-md-7">
              <div class ="navigation">
                <h1><a href="">work</a></h2>
                <h1><a href="">blog</a></h2>
                <h1><a href="">about</a></h2>
                <h1><a href="">contact</a></h2>
    </div>
            </div>
        </div>
    </div>

    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content1 %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>